# Generated by Django 3.0.3 on 2020-04-09 17:34

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_avatar_large'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default.ico', upload_to='users_avatar'),
        ),
    ]
