# Generated by Django 3.0.3 on 2020-04-13 08:21

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200409_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile_avatar.png', upload_to='users_avatar'),
        ),
    ]
